import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';
import image from "./static/img/undraw_docusaurus_react.svg"
/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */
const sidebars: SidebarsConfig = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  // tutorialSidebar: [{type: 'autogenerated', dirName: '.'}],

  // But you can create a sidebar manually
  
  tutorialSidebar: [
    'intro',
    {
      type: 'category',
      label: 'Tutorialextras',
      items: ['tutorial-extras/translate-your-site'],
      // link: {//点击category会跳转到一个没有侧边栏的 slug 对应的文章
      //   type: 'generated-index',
      //   title: 'Docusaurus Guides',
      //   description: 'Learn about the most important Docusaurus concepts!',
      //   slug: '/tutorial-basics/create-a-blog-post',
      //   keywords: ['guides'],
      //   // image: '/img/docusaurus.png',
      // },
    },
    {
      type: 'category',
      label: 'Tutorialbasics',
      items: ['tutorial-basics/create-a-document'],
      description:
      "Let's learn about the most important Docusaurus concepts!",
    },
    {
      type: 'doc',
      id: 'tutorial-extras/manage-docs-versions', // document ID
      label: 'Getting started', // sidebar label
    },
    {
      type: 'link',
      label: 'Facebook', // The link label
      href: 'https://facebook.com', // The external URL
    },
    // {//自定义侧边栏标签
    //   type: 'html',
    //   value: `<img src=`+{image} +`alt="favicon" />`, // The HTML to be rendered
    //   defaultStyle: true, // Use the default menu item styling
    // },
  ],
  
};

export default sidebars;
